name: API Test Automation with Java, TestNG and Playwright

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 20 * * 6

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'adopt'
          java-version: '16'
          cache: 'maven'
      - name: Run all tests
        run: mvn clean test
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_test_failures: true